pload/views.py
from collections import defaultdict
from dateutil.tz import gettz, UTC
import datetime
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    jsonify,
    render_template,
    request,
)
from .db import db
from .exceptions import PlaylistValidationException
from .filters import localize_datetime
from .forms import CreatePlaylistForm
from .models import Playlist, QueuedTrack
from .view_utils import process_url, get_dj_list


bp = Blueprint("pload", __name__)


@bp.route("/")
def index():
    djs = get_dj_list()
    dj_map = {int(dj["id"]): dj["airname"] for dj in djs}
    dj_map[1] = "Automation"

    tracks_sq = (
        QueuedTrack.query.with_entities(
            QueuedTrack.playlist_id,
            db.func.count(QueuedTrack.playlist_id).label("count"),
        )
        .group_by(QueuedTrack.playlist_id)
        .subquery()
    )

    playlists = (
        Playlist.query.with_entities(
            Playlist.id,
            Playlist.timeslot_start,
            Playlist.timeslot_end,
            Playlist.queue,
            Playlist.dj_id,
            tracks_sq.c.count,
        )
        .outerjoin(tracks_sq, tracks_sq.c.playlist_id == Playlist.id)
        .filter(
            Playlist.timeslot_end >= datetime.datetime.utcnow(),
            Playlist.approved != None,
        )
        .order_by(Playlist.timeslot_start)
        .all()
    )

    # localize dates and then group by them
    unplayed = defaultdict(list)
    for (
        playlist_id,
        timeslot_start,
        timeslot_end,
        queue,
        dj_id,
        track_count,
    ) in playlists:
        if dj_id is None:
            dj_id = 1

        timeslot_start = localize_datetime(timeslot_start)
        timeslot_end = localize_datetime(timeslot_end)

        unplayed[timeslot_start.date()].append(
            {
                "id": playlist_id,
                "timeslot_start": timeslot_start,
                "timeslot_end": timeslot_end,
                "queue": queue,
                "track_count": track_count or 0,
                "dj_id": dj_id,
                "dj": dj_map.get(dj_id, "[DJ #{0}]".format(dj_id)),
            }
        )

    return render_template("index.html", playlist_groups=unplayed)


@bp.route("/playlists/export/<int:playlist_id>")
def export_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)
    tracks = playlist.tracks.order_by(QueuedTrack.id)

    playlist_text = ""
    for track in tracks.all():
        playlist_text += "{0}\n".format(track.url)

    return (
        playlist_text,
        200,
        {
            "Content-Disposition": 'attachment; filename="playlist_{0}.m3u8"'.format(
                int(playlist_id)
            ),
            "Content-Type": "application/vnd.apple.mpegurl; charset=utf-8",
        },
    )


@bp.route("/playlists/edit/<int:playlist_id>", methods=["GET", "POST"])
def edit_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)

    if request.method == "POST":
        if request.headers.get("X-Requested-With") is None:
            abort(400)

        existing_tracks = QueuedTrack.query.filter(
            QueuedTrack.playlist_id == playlist_id,
        )
        if existing_tracks.filter(QueuedTrack.played == True).count() > 0:
            return jsonify(
                {
                    "success": False,
                    "results": [],
                    "message": "One or more tracks have already been played.",
                }
            )

        for track in existing_tracks.all():
            db.session.delete(track)

        index = 0
        ok = True
        results = []

        for url in request.form.getlist("tracks[]"):
            index += 1

            try:
                url = process_url(url)
            except PlaylistValidationException:
                ok = False
                results.append(
                    {
                        "index": index,
                        "url": url,
                        "status": "Error",
                    }
                )
                continue
            else:
                results.append(
                    {
                        "index": index,
                        "url": url,
                        "status": "OK",
                    }
                )

            track = QueuedTrack(url, playlist.id)
            db.session.add(track)

        if ok:
            db.session.commit()
            return jsonify(
                {
                    "success": True,
                }
            )
        else:
            db.session.rollback()
            return jsonify(
                {
                    "success": False,
                    "results": results,
                    "message": "One or more tracks failed to pass validation.",
                }
            )

    tracks = playlist.tracks.order_by(QueuedTrack.id)

    # Make sure no tracks in the playlist have been played yet
    for track in tracks.all():
        if track.played:
            return render_template(
                "playlist_being_played.html",
                playlist=playlist,
                tracks=[t.serialize() for t in tracks.all()],
            )

    return render_template(
        "edit_playlist.html",
        playlist=playlist,
        tracks=[t.serialize() for t in tracks.all()],
    )


@bp.route("/playlists/edit/<int:playlist_id>", methods=["DELETE"])
def delete_playlist(playlist_id):
    playlist = Playlist.query.get_or_404(playlist_id)

    # Make sure no tracks in the playlist have been played yet
    for track in playlist.tracks.all():
        if track.played:
            return jsonify(
                {
                    "success": False,
                    "message": "One or more tracks in the playlist have already been played.",
                }
            )

    # No tracks have been played, so mark the playlist as not approved
    # We do this instead of deleting to enable restoration of deleted playlists
    # if necessary
    playlist.approved = None
    db.session.commit()
    return jsonify(
        {
            "success": True,
        }
    )


@bp.route("/playlists/new", methods=["GET", "POST"])
def create_playlist():
    form = CreatePlaylistForm()

    # get list of DJs from Trackman and add
    djs = get_dj_list()
    form.dj_id.choices += [(str(dj["id"]), dj["airname"]) for dj in djs]

    if form.validate_on_submit():
        slot_tz = gettz(current_app.config["TIME_SLOT_TZ"])

        timeslot_start = datetime.datetime(
            form.date.data.year,
            form.date.data.month,
            form.date.data.day,
            form.time_start.data.hour,
            form.time_start.data.minute,
            tzinfo=slot_tz,
        )
        timeslot_end = datetime.datetime(
            form.date.data.year,
            form.date.data.month,
            form.date.data.day,
            form.time_end.data.hour,
            form.time_end.data.minute,
            tzinfo=slot_tz,
        )

        if timeslot_end <= timeslot_start:
            timeslot_end += datetime.timedelta(days=1)

        # convert times to UTC for querying the database
        timeslot_start = timeslot_start.astimezone(UTC)
        timeslot_end = timeslot_end.astimezone(UTC)

        if len(form.queue.data) <= 0:
            queue = None
        else:
            queue = form.queue.data

        existing_playlists = Playlist.query.filter(
            db.or_(
                # The new playlist is either exactly at the same time as an
                # existing playlist or there's an existing playlist entirely
                # inside the same time slot
                db.and_(
                    # An existing playlist starts after (inclusive) we do
                    Playlist.timeslot_start >= timeslot_start,
                    # AND that playlist ends before (inclusive) we do
                    Playlist.timeslot_end <= timeslot_end,
                ),
                # The new playlist will start before an existing playlist ends
                db.and_(
                    # An existing playlist starts before (inclusive) we do
                    Playlist.timeslot_start <= timeslot_start,
                    # AND that playlist ends after we start
                    Playlist.timeslot_end > timeslot_start,
                ),
                # The new playlist will end after an existing playlist starts
                db.and_(
                    # An existing playlist starts after (inclusive) we do
                    Playlist.timeslot_start >= timeslot_start,
                    # AND that playlist starts before we end
                    Playlist.timeslot_start < timeslot_end,
                ),
            ),
            Playlist.queue == queue,
            Playlist.approved != None,
        )

        # check for existing playlists in the same slot
        if existing_playlists.count() > 0:
            flash(
                """\
A playlist already exists that overlaps the date and time slot you selected.
You'll need to either delete the existing playlist or pick a different slot."""
            )
        else:
            playlist = Playlist(
                timeslot_start, timeslot_end, form.dj_id.data, form.queue.data
            )
            playlist.approved = datetime.datetime.utcnow()
            db.session.add(playlist)

            db.session.commit()

            return render_template(
                "edit_playlist.html",
                playlist=playlist,
                tracks=[],
            )

    return render_template("create_playlist.html", form=form)

pload/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />

        <title>{% if page_title %}{{ page_title }} &ndash; {% endif %}{{ config.PLOAD_NAME }}</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.min.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/playlist.css', v=1) }}" />
    </head>
    <body{% block bodyattrib %}{% endblock %}>
{% block header %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
            <div class="{% if wide_page %}container-fluid{% else %}container{% endif %}">
                <a class="navbar-brand" href="{{ url_for('pload.index') }}">{{ config.PLOAD_NAME }}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#admin-top-navbar" aria-controls="admin-top-navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="admin-top-navbar">
                    <ul class="nav navbar-nav">
                        {% block nav_index %}<li class="nav-item"><a class="nav-link" href="{{ url_for('pload.index') }}">Scheduled Playlists</a></li>{% endblock %}
                        {% block nav_create %}<li class="nav-item"><a class="nav-link" href="{{ url_for('pload.create_playlist') }}">Create Playlist</a></li>{% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
{% endblock %}

<div class="container">
    {% for msg in get_flashed_messages() %}
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ msg }}
    </div>
    {% endfor %}
</div>

<div class="container-fluid">
{% block content %}
{% endblock %}
</div>

{% block js %}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
    </body>
</html>

pload/templates/create_playlist.html
{% extends "base.html" %}
{% block nav_create %}<li class="nav-item"><a class="nav-link active" href="{{ url_for('pload.create_playlist') }}">Create Playlist</a></li>{% endblock %}
{% block content %}
<div class="container">
<h1>Create Playlist</h1>

<form method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <div class="form-group row{% if form.queue.errors|length > 0 %} has-error{% endif %}">
        {{ form.queue.label(class_="col-sm-3 col-form-label control-label") }}
        <div class="col-sm-9">
            {{ form.queue }}
{% for error in form.queue.errors %}
            <div class="help-block">{{ error }}</div>
{% endfor %}
        </div>
    </div>

    <div class="form-group row{% if form.date.errors|length > 0 %} has-error{% endif %}">
        {{ form.date.label(class_="col-sm-3 col-form-label control-label") }}
        <div class="col-sm-9">
            {{ form.date }}
{% for error in form.date.errors %}
            <div class="help-block">{{ error }}</div>
{% endfor %}
        </div>
    </div>

    <div class="form-group row{% if form.time_start.errors|length > 0 %} has-error{% endif %}">
        {{ form.time_start.label(class_="col-sm-3 col-form-label control-label") }}
        <div class="col-sm-9">
            {{ form.time_start }}
{% for error in form.time_start.errors %}
            <div class="help-block">{{ error }}</div>
{% endfor %}
        </div>
    </div>

    <div class="form-group row{% if form.time_end.errors|length > 0 %} has-error{% endif %}">
        {{ form.time_end.label(class_="col-sm-3 col-form-label control-label") }}
        <div class="col-sm-9">
            {{ form.time_end }}
{% for error in form.time_end.errors %}
            <div class="help-block">{{ error }}</div>
{% endfor %}
        </div>
    </div>

    <div class="form-group row{% if form.dj_id.errors|length > 0 %} has-error{% endif %}">
        {{ form.dj_id.label(class_="col-sm-3 col-form-label control-label") }}
        <div class="col-sm-9">
            {{ form.dj_id }}
{% for error in form.dj_id.errors %}
            <div class="help-block">{{ error }}</div>
{% endfor %}
        </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            Create
        </button>
    </div>
</form>
</div>
{% endblock %}

pload/templates/edit_playlist.html
{% set return_url = url_for('pload.index') %}
{% extends "playlist_editor.html" %}
{% block js %}
{{ super() }}
<script nonce="{{ script_nonce }}">
var playlistEditor = new PlaylistEditor("{{ url_for('pload.index', _external=True)[:-1] }}");
playlistEditor.displayRewrites = {{ config.TRACK_URL_DISPLAY_REWRITES|tojson }};
playlistEditor.init();
playlistEditor.loadPlaylist({{ tracks|tojson }});

$('#save_changes_btn').on('click', function(ev) {
    $('#save_changes_btn').prop('disabled', true);

    $.ajax({
        url: "{{ url_for('pload.edit_playlist', playlist_id=playlist.id) }}",
        method: "POST",
        dataType: "json",
        data: {
            tracks: playlistEditor.listTracks(),
        },
        success: function(data) {
            if(data['success']) {
                window.location.href = "{{ url_for('pload.index') }}";
            } else {
                if(typeof data['message'] != 'undefined') {
                    alert(data['message']);
                } else {
                    alert("An error occurred while saving the playlist.");
                }

                // highlight tracks that failed, if they are present in the response
                if(typeof data['results'] == 'object') {
                    for(let i = 0; i < data['results'].length; i++) {
                        let row = $('#playlist tr[data-playlist-id=' + i + ']');
                        if(typeof row != 'undefined') {
                            row.addClass('table-danger');
                            row.attr('title', "An error occurred with this track. Please double check it and try again.");
                        }
                    }
                }
            }

            $('#save_changes_btn').prop('disabled', false);
        },
        error: function(data) {
            alert("An error occurred while saving the playlist.");
            $('#save_changes_btn').prop('disabled', false);
        },
    });
});
</script>
{% endblock %}

pload/templates/index.html
{% extends "base.html" %}
{% block nav_index %}<li class="nav-item"><a class="nav-link active" href="{{ url_for('pload.index') }}">Scheduled Playlists</a></li>{% endblock %}
{% block content %}
<div class="container">
<h1>Scheduled Playlists</h1>

{% for date, playlists in playlist_groups.items() %}
<div class="card mt-1">
    <div class="card-header">
        {{ date|datetime("%Y-%m-%d", False) }}
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <th scope="col" width="25%"></th>
            <th scope="col" width="35%">DJ</th>
            <th scope="col" width="10%">Tracks</th>
            <th scope="col" width="10%">Start Time</th>
            <th scope="col" width="10%">End Time</th>
            <th scope="col" width="10%"></th>
        </thead>
        <tbody>
{% for playlist in playlists %}
            <tr data-playlist-id="{{ playlist.id }}">
                <td>{% if playlist.queue != "prerecorded" %}Playlist{% else %}Prerecorded Show{% endif %}</td>
                <td>{{ playlist.dj }}</td>
                <td>{{ playlist.track_count }}</td>
                <td>{{ playlist.timeslot_start|datetime("%H:%M", False) }}</td>
                <td>{{ playlist.timeslot_end|datetime("%H:%M", False) }}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <a href="{{ url_for('pload.export_playlist', playlist_id=playlist.id) }}" class="btn btn-secondary btn-sm playlist-edit" title="Export this playlist as an M3U8 file"><span class="oi oi-cloud-download"></span></a>
                        <a href="{{ url_for('pload.edit_playlist', playlist_id=playlist.id) }}" class="btn btn-secondary btn-sm playlist-edit" title="Edit this playlist"><span class="oi oi-pencil"></span></a>
                        <button class="btn btn-danger btn-sm playlist-delete" title="Delete this playlist"><span class="oi oi-trash"></span></button>
                    </div>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
{% endfor %}
{% endblock %}
{% block js %}
{{ super() }}
<script nonce="{{ script_nonce }}">
$('button.playlist-delete').on('click', function(ev) {
    var row = $(this).parents('tr');
    var playlistId = row.attr('data-playlist-id');

    if(!confirm("Are you sure you want to delete the selected playlist?")) {
        return;
    }

    $.ajax({
        url: "/playlists/edit/" + playlistId,
        method: "DELETE",
        dataType: "json",
        success: function(data) {
            if(data['success']) {
                row.remove();
            } else {
                if(typeof data['message'] != 'undefined') {
                    alert(data['message']);
                } else {
                    alert("An error occurred while deleting that playlist.");
                }
            }
        },
        error: function(data) {
            alert("An error occurred while deleting that playlist.");
        },
    });
});
</script>
{% endblock %}

pload/templates/playlist_being_played.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h1>Playlist</h1>

<p>This playlist has already started playing and cannot be edited.</p>

<div class="card mt-1">
    <div class="card-body">
        <h5 class="card-title">{% if playlist.queue != "prerecorded" %}Playlist{% else %}Prerecorded Show{% endif %}</h5>
        <p class="card-text">Scheduled to play between {{ playlist.timeslot_start|datetime }} and {{ playlist.timeslot_end|datetime }}.</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">URL</th>
                <th scope="col">Played</th>
            </tr>
        </thead>
        <tbody>
{% for track in tracks %}
            <tr>
                <td><a href="{{ track.url|public_url }}">{{ track.url|public_url|urldecode|wordwrap }}</a></td>
                <td>{{ track.played }}</td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

pload/templates/playlist_editor.html
{% set wide_page = true %}
{% extends "base.html" %}
{% block content %}
<h1>{% if playlist_editor_title %}{{ playlist_editor_title }}{% else %}Playlist Editor{% endif %}</h1>

<div class="floating-alerts" id="playlist_alerts"></div>

<div class="card mt-1" id="playlist_card">
    <div class="card-body">
        <div class="float-right">
            {% if return_url %}<a href="{{ return_url }}" class="btn btn-secondary">Cancel</a>{% endif %}
            <button type="button" id="save_changes_btn" class="btn btn-primary">{% if save_changes_btn_label %}{{ save_changes_btn_label }}{% else %}Save Changes{% endif %}</button>
        </div>
        <h5 class="card-title">{% if playlist.queue == "prerecorded" %}Prerecorded Show{% else %}Playlist{% endif %}</h5>
        <p class="card-text">Scheduled to play between {{ playlist.timeslot_start|datetime }} and {{ playlist.timeslot_end|datetime }}.</p>
    </div>

    <table class="table table-condensed mb-0" id="playlist_header">
        <thead>
            <tr>
                <th>Offset</th>
                <th>Artist</th>
                <th>Title</th>
                <th>Album</th>
                <th>Label</th>
                <th>Length</th>
                <th></th>
            </tr>
        </thead>
    </table>
    <div id="playlist_container">
        <table class="table table-condensed table-striped table-hover" id="playlist">
            <colgroup>
                <col class="offset"></col>
                <col class="artist"></col>
                <col class="title"></col>
                <col class="album"></col>
                <col class="label"></col>
                <col class="length"></col>
                <col></col>
            </colgroup>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="card mt-1" id="search_container">
    <div class="card-body">
        <form id="playlist_search_form">
            <div class="form-group d-flex mb-0">
                <div class="flex-grow-1">
                    <input type="text" name="q" id="q" value="" class="form-control" placeholder="Search for tracks" title="Enter a query to search for tracks"/>
                </div>
                <div class="pl-2">
                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                        <button type="button" id="search_tracks_btn" class="btn btn-info">
                            <span class="oi oi-magnifying-glass"></span>
                            Search
                        </button>

                        <div class="btn-group" role="group">
                            <button type="button" id="advanced_btn" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="sr-only">Toggle Advanced Options</span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labeledby="advanced_btn">
                                <button type="button" id="add_by_url" class="dropdown-item"
                                        data-toggle="modal" data-target="#add_by_url_modal">
                                    Add Track by URL
                                </button>
                                <button type="button" id="import_m3u" class="dropdown-item"
                                        data-toggle="modal" data-target="#import_m3u_modal">
                                    Import M3U
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <table class='table table-condensed mb-0' id="search_results_header">
        <thead title="These are your track search results. When you enter a query above, results will appear here.">
            <tr>
                <th>Artist</th>
                <th>Title</th>
                <th>Album</th>
                <th>Label</th>
                <th>Length</th>
                <th>URL</th>
                <th></th>
            </tr>
        </thead>
    </table>

    <div id="search_results_container">
        <table class='table table-condensed table-striped table-hover mb-0' id="search_results">
            <colgroup>
                <col class="artist"></col>
                <col class="title"></col>
                <col class="album"></col>
                <col class="label"></col>
                <col class="length"></col>
                <col class="url"></col>
                <col></col>
            </colgroup>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div id="add_by_url_modal" role="dialog" class="modal fade" tabindex="-1"
        aria-labelledby="add_by_url_modal_label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="add_by_url_modal_label">
                    Add Track by URL
                </h4>
                <button type="button" class="close" aria-label="Close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form id="add_by_url_form">
                <div class="modal-body">
                    <p>This URL must be accessible from the WUVT network; local
                    files on your computer will not work.</p>

                    <div class="form-group">
                        <label for="url">URL</label>
                        <input type="text" name="url" id="url" value="" class="form-control"/>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Cancel
                    </button>
                    <button type="submit" id="add_by_url_submit_btn" class="btn btn-primary">
                        Add Track
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="import_m3u_modal" role="dialog" class="modal fade" tabindex="-1"
        aria-labelledby="import_m3u_modal_label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="import_m3u_modal_label">
                    Import M3U
                </h4>
                <button type="button" class="close" aria-label="Close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Upload only .m3u or .m3u8 playlists. Every item in the
                playlist must be a URL that is accessible from the WUVT
                network; local files on your computer will not work.</p>

                <div class="form-group">
                    <label for="import_m3u_input">.m3u (or .m3u8) playlist file</label>
                    <input type="file" class="form-control-file" id="import_m3u_input"/>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-dismiss="modal">
                    Cancel
                </button>
                <button id="import_m3u_submit_btn" class="btn btn-primary">
                    Import M3U
                </button>
            </div>
        </div>
    </div>
</div>

<div id="track_info_modal" role="dialog" class="modal fade" tabindex="-1"
        aria-labelledby="track_info_modal_label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="track_info_modal_label">
                    Track Info
                </h4>
                <button type="button" class="close" aria-label="Close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <dl>
                    <dt>URL</dt>
                    <dd><span id="track_info_url_container"></span></dd>
                </dl>

                <dl>
                    <dt>Bit Rate</dt>
                    <dd><span id="track_info_bitrate_container"></span> kbps</dd>
                </dl>

                <dl>
                    <dt>Sample Rate</dt>
                    <dd><span id="track_info_sample_container"></span> kHz</dd>
                </dl>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{{ super() }}
<script src="{{ url_for('static', filename='js/playlist_editor.js', v=10) }}"></script>
{% endblock %}